version: '2'
services:
    web:
        build: .
        environment:
            - FLASK_ENV=development
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis:5.0